
package eseo.sw;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-04-04T14:49:15.311+02:00
 * Generated source version: 3.2.1
 * 
 */
public final class GestionHotelsSEI_GestionHotelsPort_Client {

    private static final QName SERVICE_NAME = new QName("http://sw.eseo/", "GestionHotelsService");

    private GestionHotelsSEI_GestionHotelsPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GestionHotelsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GestionHotelsService ss = new GestionHotelsService(wsdlURL, SERVICE_NAME);
        GestionHotelsSEI port = ss.getGestionHotelsPort();  
        
        {
        System.out.println("Invoking payerChambre...");
        int _payerChambre_arg0 = -65239715;
        java.lang.String _payerChambre__return = port.payerChambre(_payerChambre_arg0);
        System.out.println("payerChambre.result=" + _payerChambre__return);


        }
        {
        System.out.println("Invoking annulerChambre...");
        int _annulerChambre_arg0 = 1448880593;
        boolean _annulerChambre__return = port.annulerChambre(_annulerChambre_arg0);
        System.out.println("annulerChambre.result=" + _annulerChambre__return);


        }
        {
        System.out.println("Invoking reserverChambre...");
        eseo.sw.ReservationChambre _reserverChambre_arg0 = new eseo.sw.ReservationChambre();
        _reserverChambre_arg0.setDateDebut(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-04-04T14:49:15.414+02:00"));
        _reserverChambre_arg0.setDateFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-04-04T14:49:15.415+02:00"));
        _reserverChambre_arg0.setIdChambre(2015766250);
        _reserverChambre_arg0.setIdClient(-1121841997);
        _reserverChambre_arg0.setIdReservation(1275793356);
        _reserverChambre_arg0.setNbPlaces(-1351992476);
        _reserverChambre_arg0.setPaiementEffectue(false);
        int _reserverChambre__return = port.reserverChambre(_reserverChambre_arg0);
        System.out.println("reserverChambre.result=" + _reserverChambre__return);


        }
        {
        System.out.println("Invoking trouverChambre...");
        eseo.sw.Chambre _trouverChambre_arg0 = new eseo.sw.Chambre();
        _trouverChambre_arg0.setEtage(-2137662372);
        _trouverChambre_arg0.setIdChambre(1878880443);
        _trouverChambre_arg0.setNbLits(-1808344321);
        _trouverChambre_arg0.setPrix(-18950467);
        _trouverChambre_arg0.setTypeChambre("TypeChambre752783700");
        java.util.List<eseo.sw.Chambre> _trouverChambre__return = port.trouverChambre(_trouverChambre_arg0);
        System.out.println("trouverChambre.result=" + _trouverChambre__return);


        }

        System.exit(0);
    }

}
