
package fr.eseo.jee.agence.velo.sw2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-03-29T17:47:35.477+02:00
 * Generated source version: 3.2.1
 * 
 */
public final class LocationSEI_LocationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://sw.velo.agence.jee.eseo.fr/", "LocationService");

    private LocationSEI_LocationPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LocationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LocationService ss = new LocationService(wsdlURL, SERVICE_NAME);
        LocationSEI port = ss.getLocationPort();  
        
        {
        System.out.println("Invoking annulerVelo...");
        int _annulerVelo_arg0 = 858180301;
        boolean _annulerVelo__return = port.annulerVelo(_annulerVelo_arg0);
        System.out.println("annulerVelo.result=" + _annulerVelo__return);


        }
        {
        System.out.println("Invoking reserverVelo...");
        fr.eseo.jee.agence.velo.sw2.ReservationVelo _reserverVelo_arg0 = new fr.eseo.jee.agence.velo.sw2.ReservationVelo();
        _reserverVelo_arg0.setCodeClient(1791124764);
        _reserverVelo_arg0.setCodeReservation(-240448045);
        _reserverVelo_arg0.setCodeVelo(-1073321914);
        _reserverVelo_arg0.setDateDebut("DateDebut-1837839625");
        _reserverVelo_arg0.setDateFin("DateFin802021781");
        _reserverVelo_arg0.setPaiementEffectue(false);
        int _reserverVelo__return = port.reserverVelo(_reserverVelo_arg0);
        System.out.println("reserverVelo.result=" + _reserverVelo__return);


        }
        {
        System.out.println("Invoking trouverVelo...");
        fr.eseo.jee.agence.velo.sw2.Velo _trouverVelo_arg0 = new fr.eseo.jee.agence.velo.sw2.Velo();
        _trouverVelo_arg0.setCategorie("Categorie1650333896");
        _trouverVelo_arg0.setCodeVelo(2097448741);
        _trouverVelo_arg0.setPrixLocation(0.9110392654974103);
        _trouverVelo_arg0.setVille("Ville860729143");
        java.util.List<fr.eseo.jee.agence.velo.sw2.Velo> _trouverVelo__return = port.trouverVelo(_trouverVelo_arg0);
        System.out.println("trouverVelo.result=" + _trouverVelo__return);


        }
        {
        System.out.println("Invoking payerVelo...");
        int _payerVelo_arg0 = -1475616605;
        java.lang.String _payerVelo__return = port.payerVelo(_payerVelo_arg0);
        System.out.println("payerVelo.result=" + _payerVelo__return);


        }

        System.exit(0);
    }

}
