package fr.eseo.jee.agence.velo.sw2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-03-29T17:47:36.382+02:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://sw.velo.agence.jee.eseo.fr/", name = "LocationSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface LocationSEI {

    @WebMethod
    @RequestWrapper(localName = "annulerVelo", targetNamespace = "http://sw.velo.agence.jee.eseo.fr/", className = "fr.eseo.jee.agence.velo.sw2.AnnulerVelo")
    @ResponseWrapper(localName = "annulerVeloResponse", targetNamespace = "http://sw.velo.agence.jee.eseo.fr/", className = "fr.eseo.jee.agence.velo.sw2.AnnulerVeloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerVelo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "reserverVelo", targetNamespace = "http://sw.velo.agence.jee.eseo.fr/", className = "fr.eseo.jee.agence.velo.sw2.ReserverVelo")
    @ResponseWrapper(localName = "reserverVeloResponse", targetNamespace = "http://sw.velo.agence.jee.eseo.fr/", className = "fr.eseo.jee.agence.velo.sw2.ReserverVeloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverVelo(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.jee.agence.velo.sw2.ReservationVelo arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverVelo", targetNamespace = "http://sw.velo.agence.jee.eseo.fr/", className = "fr.eseo.jee.agence.velo.sw2.TrouverVelo")
    @ResponseWrapper(localName = "trouverVeloResponse", targetNamespace = "http://sw.velo.agence.jee.eseo.fr/", className = "fr.eseo.jee.agence.velo.sw2.TrouverVeloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.jee.agence.velo.sw2.Velo> trouverVelo(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.jee.agence.velo.sw2.Velo arg0
    );

    @WebMethod
    @RequestWrapper(localName = "payerVelo", targetNamespace = "http://sw.velo.agence.jee.eseo.fr/", className = "fr.eseo.jee.agence.velo.sw2.PayerVelo")
    @ResponseWrapper(localName = "payerVeloResponse", targetNamespace = "http://sw.velo.agence.jee.eseo.fr/", className = "fr.eseo.jee.agence.velo.sw2.PayerVeloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String payerVelo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
