
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.jee.agence.velo.sw2;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-03-29T17:47:36.024+02:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "LocationService",
                      portName = "LocationPort",
                      targetNamespace = "http://sw.velo.agence.jee.eseo.fr/",
                      wsdlLocation = "http://localhost:8080/GestionCompagnieVelo/services/LocationPort?wsdl",
                      endpointInterface = "fr.eseo.jee.agence.velo.sw2.LocationSEI")
                      
public class LocationPortImpl implements LocationSEI {

    private static final Logger LOG = Logger.getLogger(LocationPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.jee.agence.velo.sw2.LocationSEI#annulerVelo(int arg0)*
     */
    public boolean annulerVelo(int arg0) { 
        LOG.info("Executing operation annulerVelo");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.agence.velo.sw2.LocationSEI#reserverVelo(fr.eseo.jee.agence.velo.sw2.ReservationVelo arg0)*
     */
    public int reserverVelo(fr.eseo.jee.agence.velo.sw2.ReservationVelo arg0) { 
        LOG.info("Executing operation reserverVelo");
        System.out.println(arg0);
        try {
            int _return = 1242507976;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.agence.velo.sw2.LocationSEI#trouverVelo(fr.eseo.jee.agence.velo.sw2.Velo arg0)*
     */
    public java.util.List<fr.eseo.jee.agence.velo.sw2.Velo> trouverVelo(fr.eseo.jee.agence.velo.sw2.Velo arg0) { 
        LOG.info("Executing operation trouverVelo");
        System.out.println(arg0);
        try {
            java.util.List<fr.eseo.jee.agence.velo.sw2.Velo> _return = new java.util.ArrayList<fr.eseo.jee.agence.velo.sw2.Velo>();
            fr.eseo.jee.agence.velo.sw2.Velo _returnVal1 = new fr.eseo.jee.agence.velo.sw2.Velo();
            _returnVal1.setCategorie("Categorie1318606493");
            _returnVal1.setCodeVelo(1515645520);
            _returnVal1.setPrixLocation(0.8108371397244767);
            _returnVal1.setVille("Ville-583201399");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.agence.velo.sw2.LocationSEI#payerVelo(int arg0)*
     */
    public java.lang.String payerVelo(int arg0) { 
        LOG.info("Executing operation payerVelo");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-394763082";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
