package fr.eseo.jee.agence.velo.sw;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-03-26T14:34:05.948+02:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "LocationService", 
                  wsdlLocation = "file:/home/lubuntu/git/IHMReservationVelo/IHMReservationVelo/wdslServeur/location.wsdl",
                  targetNamespace = "http://sw.velo.agence.jee.eseo.fr/") 
public class LocationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sw.velo.agence.jee.eseo.fr/", "LocationService");
    public final static QName LocationPort = new QName("http://sw.velo.agence.jee.eseo.fr/", "LocationPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/lubuntu/git/IHMReservationVelo/IHMReservationVelo/wdslServeur/location.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LocationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/lubuntu/git/IHMReservationVelo/IHMReservationVelo/wdslServeur/location.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LocationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LocationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LocationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LocationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LocationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LocationSEI
     */
    @WebEndpoint(name = "LocationPort")
    public LocationSEI getLocationPort() {
        return super.getPort(LocationPort, LocationSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocationSEI
     */
    @WebEndpoint(name = "LocationPort")
    public LocationSEI getLocationPort(WebServiceFeature... features) {
        return super.getPort(LocationPort, LocationSEI.class, features);
    }

}
