
package fr.eseo.jee.agence.velo.sw;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-03-26T14:34:05.124+02:00
 * Generated source version: 3.2.1
 * 
 */
public final class LocationSEI_LocationPort_Client {

    private static final QName SERVICE_NAME = new QName("http://sw.velo.agence.jee.eseo.fr/", "LocationService");

    private LocationSEI_LocationPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LocationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LocationService ss = new LocationService(wsdlURL, SERVICE_NAME);
        LocationSEI port = ss.getLocationPort();  
        
        {
        System.out.println("Invoking annulerVelo...");
        int _annulerVelo_arg0 = 1673670641;
        boolean _annulerVelo__return = port.annulerVelo(_annulerVelo_arg0);
        System.out.println("annulerVelo.result=" + _annulerVelo__return);


        }
        {
        System.out.println("Invoking reserverVelo...");
        fr.eseo.jee.agence.velo.sw.ReservationVelo _reserverVelo_arg0 = new fr.eseo.jee.agence.velo.sw.ReservationVelo();
        _reserverVelo_arg0.setCodeClient(-926283220);
        _reserverVelo_arg0.setCodeReservation(-1781925458);
        _reserverVelo_arg0.setCodeVelo(-593985431);
        fr.eseo.jee.agence.velo.sw.Date _reserverVelo_arg0DateDebut = new fr.eseo.jee.agence.velo.sw.Date();
        _reserverVelo_arg0.setDateDebut(_reserverVelo_arg0DateDebut);
        fr.eseo.jee.agence.velo.sw.Date _reserverVelo_arg0DateFin = new fr.eseo.jee.agence.velo.sw.Date();
        _reserverVelo_arg0.setDateFin(_reserverVelo_arg0DateFin);
        _reserverVelo_arg0.setPaiementEffectue(false);
        int _reserverVelo__return = port.reserverVelo(_reserverVelo_arg0);
        System.out.println("reserverVelo.result=" + _reserverVelo__return);


        }
        {
        System.out.println("Invoking trouverVelo...");
        fr.eseo.jee.agence.velo.sw.Velo _trouverVelo_arg0 = new fr.eseo.jee.agence.velo.sw.Velo();
        _trouverVelo_arg0.setCategorie("Categorie-374416142");
        _trouverVelo_arg0.setCodeVelo(1863149561);
        _trouverVelo_arg0.setPrixLocation(0.4886945217383819);
        _trouverVelo_arg0.setVille("Ville-746703532");
        java.util.List<fr.eseo.jee.agence.velo.sw.Velo> _trouverVelo__return = port.trouverVelo(_trouverVelo_arg0);
        System.out.println("trouverVelo.result=" + _trouverVelo__return);


        }
        {
        System.out.println("Invoking payerVelo...");
        int _payerVelo_arg0 = -788451047;
        java.lang.String _payerVelo__return = port.payerVelo(_payerVelo_arg0);
        System.out.println("payerVelo.result=" + _payerVelo__return);


        }

        System.exit(0);
    }

}
