
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.jee.agence.hotel.sw;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-04-04T14:49:15.417+02:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "GestionHotelsService",
                      portName = "GestionHotelsPort",
                      targetNamespace = "http://sw.eseo/",
                      wsdlLocation = "http://192.168.4.78:8085/services/GestionHotelsPort?wsdl",
                      endpointInterface = "eseo.sw.GestionHotelsSEI")
                      
public class GestionHotelsPortImpl implements GestionHotelsSEI {

    private static final Logger LOG = Logger.getLogger(GestionHotelsPortImpl.class.getName());

    /* (non-Javadoc)
     * @see eseo.sw.GestionHotelsSEI#payerChambre(int arg0)*
     */
    public java.lang.String payerChambre(int arg0) { 
        LOG.info("Executing operation payerChambre");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1753841846";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eseo.sw.GestionHotelsSEI#annulerChambre(int arg0)*
     */
    public boolean annulerChambre(int arg0) { 
        LOG.info("Executing operation annulerChambre");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eseo.sw.GestionHotelsSEI#reserverChambre(eseo.sw.ReservationChambre arg0)*
     */
    public int reserverChambre(fr.eseo.jee.agence.hotel.sw.ReservationChambre arg0) { 
        LOG.info("Executing operation reserverChambre");
        System.out.println(arg0);
        try {
            int _return = 1224213405;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see eseo.sw.GestionHotelsSEI#trouverChambre(eseo.sw.Chambre arg0)*
     */
    public java.util.List<fr.eseo.jee.agence.hotel.sw.Chambre> trouverChambre(fr.eseo.jee.agence.hotel.sw.Chambre arg0) { 
        LOG.info("Executing operation trouverChambre");
        System.out.println(arg0);
        try {
            java.util.List<fr.eseo.jee.agence.hotel.sw.Chambre> _return = new java.util.ArrayList<fr.eseo.jee.agence.hotel.sw.Chambre>();
            fr.eseo.jee.agence.hotel.sw.Chambre _returnVal1 = new fr.eseo.jee.agence.hotel.sw.Chambre();
            _returnVal1.setEtage(1595032624);
            _returnVal1.setIdChambre(1068329167);
            _returnVal1.setNbLits(770780719);
            _returnVal1.setPrix(817086860);
            _returnVal1.setTypeChambre("TypeChambre943196711");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
